#!/usr/bin/env python
import sys
import string
import smtplib
from email.mime.text import MIMEText
import platform
​
​
# VAR
# main settings:
mail_from = 'no-reply-service@pls.life'
smtp_server = 'smtp-relay.gmail.com'
​
​
​
def send_mail(msg, mail_recipients):
    # mail_recp - type list -  mail recipients
    hostname = platform.node()
    msg = MIMEText(msg)
    msg['Subject'] = 'Test mail:{}'.format(hostname)
    msg['From'] = mail_from
    try:
        for rcp in mail_recipients:
            msg['To'] = rcp
            s = smtplib.SMTP_SSL(smtp_server, timeout=20, port=465)
            s.sendmail(mail_from, [rcp], msg.as_string())
            s.quit()
        print('Mail send successfull!')
    except Exception as e:
        print('ERROR: send mail. ' + str(e))
        sys.exit(0)
​
send_mail('test',['YOUR_EMAIL'])
